from typing import Protocol


class GitClient(Protocol):
    """Future subprocess boundary; deliberately has no force-push operation."""

    def status_porcelain(self) -> str: ...
    def fetch(self, remote: str) -> None: ...
    def head_sha(self) -> str: ...
    def commit(self, message: str) -> str: ...
    def push(self, remote: str, branch: str) -> None: ...

